#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
;# script wasn't run conservatively originally
if {$force_conservative} {
set send_slow {1 .1}
proc send {ignore arg} {
sleep .1
exp_send -s -- $arg
}
}

set timeout -1
set password [lindex $argv 0];
spawn openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -out keystore.p12 -name tomcat -CAfile chain.penanom -caname root
match_max 100000
expect -exact "Enter Export Password:"
send -- "$password\r"
expect "Verifying - Enter Export Password:"
send -- "$password\r"
expect eof
