AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for Jarvis application.
Resources:
  WebServer:
    Type: AWS::Lightsail::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Properties:
      BlueprintId: ubuntu_20_04
      BundleId: nano_2_0
      InstanceName: jarvis-server
      KeyPairName: jarvis-frankfurt
      Networking:
        Ports:
          - AccessDirection: inbound
            FromPort: 8080
            ToPort: 8080
            CommonName: Application port
          - AccessDirection: inbound
            FromPort: 1883
            ToPort: 1883
            CommonName: MQTT topic port
          - AccessDirection: inbound
            FromPort: 22
            ToPort: 22
            CommonName: SSH port
      UserData: |
        #!/bin/bash
        apt-get update -y
        apt-get install default-jre -y
        apt-get install make -y
        apt-get install gcc -y
        apt-get install expect -y
        apt-get install mosquitto -y
        touch /etc/mosquitto/conf.d/default.conf
        echo "listener 1883 0.0.0.0" >> /etc/mosquitto/conf.d/default.conf
        echo "set_tcp_nodelay true" >> /etc/mosquitto/conf.d/default.conf
        service mosquitto restart
        snap install --classic certbot
        ln -s /snap/bin/certbot /usr/bin/certbot
        cd /usr/local/bin/
        wget http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz
        tar xzf noip-duc-linux.tar.gz
        cd noip-2.1.9-1
        make
        aws s3 cp s3://jarvis-alexmikhalochkin/noip-init . --region eu-central-1
        chmod +x noip-init
        ./noip-init
        rm noip-init
        cd ..
        noip2
        
