#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
  ;# script wasn't run conservatively originally
if {$force_conservative} {
set send_slow {1 .1}
proc send {ignore arg} {
sleep .1
exp_send -s -- $arg
}
}

set timeout -1
set email [lindex $argv 0];
set password [lindex $argv 1];
set dns [lindex $argv 2];
spawn make install
match_max 100000
expect -exact "if \[ ! -d /usr/local/bin \]; then mkdir -p /usr/local/bin;fi\r
if \[ ! -d /usr/local/etc \]; then mkdir -p /usr/local/etc;fi\r
cp noip2 /usr/local/bin/noip2\r
/usr/local/bin/noip2 -C -c /tmp/no-ip2.conf\r
\r
Auto configuration for Linux client of no-ip.com.\r
\r
Please enter the login/email string for no-ip.com  "
send -- "$email"
expect -exact "$email"
send -- "\r"
expect -exact "\r
Please enter the password for user '$email'  "
send -- "$password"
expect -exact "***************"
send -- "\r"
expect -exact "\r
\r
Only one host \[$dns\] is registered to this account.\r
It will be used.\r
Please enter an update interval:\[30\]  "
send -- "30\r"
expect -exact "30\r
Do you wish to run something at successful update?\[N\] (y/N)  "
send -- "N"
expect eof
