spring:
  application:
    name: jarvis
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: dev
cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false
mqtt:
  server:
    url: tcp://localhost:1883
smart:
  things:
    url: https://c2c-eu.smartthings.com
yandex:
  notification:
    url: https://dialogs.yandex.net/api/v1/skills/${yandex.skill.id}/callback/state
---
spring:
  profiles: prod
security:
  require-ssl: true
server:
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias=: tomcat
---
spring:
  profiles: dev
smart:
  things:
    client:
      id: clientId
      secret: clientSecret
yandex:
  skill:
    id: 123456
  token: 123456
  user:
    id: user-id
