server.port=8080
security.require-ssl=true
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=123456
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat
jarvis.id.port.mapping={'kitchen-light-0':7,'bedroom-light-0':8, 'hallway-light-0':9}
plc.megad.url=http://192.168.100.14/sec/
