mqtt:
  active: mosquitto # aws or mosquitto
  mosquitto:
    server-url: tcp://localhost:1883
    username: username
    password: password
    listener-client-id: listener
    publisher-client-id: publisher

megad:
  id: megad-id
  url: http://localhost:8080/password/
  states:
    refresh-interval-minutes: 1440
    initial-delay-minutes: 5
    interval-between-messages-seconds: 1

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

spring:
  jackson:
    default-property-inclusion: non_null

smart-things:
  client:
    id: clientId
    secret: clientSecret
  url: https://c2c-eu.smartthings.com
  callback:
    url: https://c2c-eu.smartthings.com/device/events
    token-url: https://c2c-eu.smartthings.com/oauth/token
    refresh-token: refreshToken

yandex:
  notification-url: https://dialogs.yandex.net/api/v1/skills/${yandex.skill-id}/callback/state
  skill-id: 123456
  token: 123456
  user-id: user-id

client:
  retry:
    max-attempts: 3
    delay-millis: 5000

configured-devices:
  devices:
    - id: "kitchen-light-0"
      room:
        primaryName: "Kitchen"
        additionalName: "Кухня"
      name:
        primaryName: "Kitchen Bulb"
        additionalName: "свет на кухне"
      description: "цветная лампа"
      groups:
        - "Kitchen Lights"
        - "House Bulbs"
      sourceChannel: "MegaD"
      additionalData:
        port: 7
