version: 2.1
orbs:
  codecov: codecov/codecov@1.2.5
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run: ./gradlew build

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/reports

      - codecov/upload:
          file: build/reports/jacoco/report.xml

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

workflows:
  version: 2
  workflow:
    jobs:
      - build
