mqtt:
  server-url: tcp://localhost:1883

spring:
  jackson:
    default-property-inclusion: non_null

security:
  require-ssl: true

server:
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

smart-things:
    client:
      id: clientId
      secret: clientSecret
    url: https://c2c-eu.smartthings.com

yandex:
  skill-id: 123456
  token: 123456
  user-id: user-id
  notification-url: http://localhost:12345/api/v1/skills/${yandex.skill-id}/callback/state

client:
  retry:
    max-attempts: 3
    delay-millis: 50
