# This workflow checks a Java project on a daily basis
name: Build. Nightly

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle wrapper
      run: ./gradlew check
