name: Create infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/JarvisGithubRole
        aws-region: eu-central-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws cloudformation create-stack --stack-name jarvis-stack --template-body file://.cloudformation/jarvis-stack.yaml --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/JarvisCloudFormationLightsailRole
