# Create a droplet from the snapshot
name: Infrastructure. Scale
run-name: ${{ inputs.ssh_port_action }} SSH port

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        - name: Create a DigitalOcean droplet from the snapshot
          run: doctl compute droplet create momomo-server --size s-1vcpu-512mb-10gb --image momomo-snapshot --region fra1 --enable-monitoring
