# Create or remove an infrastructure for the application
name: Infrastructure. Scale
run-name: Scale ${{ inputs.server_scaling_action }}

on:
  workflow_dispatch:
    inputs:
      server_scaling_action:
        description: 'Up to create an infrastructure, Down to remove it'
        required: true
        type: choice
        options:
          - Up
          - Down

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        - if:  ${{ inputs.server_scaling_action == 'Up' }} 
          name: Scale Up
          run: doctl compute droplet create momomo-server --size s-1vcpu-1gb --image 157703667 --region fra1 --enable-monitoring --ssh-keys 24:99:80:38:63:54:9a:a3:0e:98:8e:2c:f8:69:f1:9b
        - if:  ${{ inputs.server_scaling_action == 'Up' }} 
          name: Add firewall to the droplet
          run: doctl compute firewall add-droplets ${{ secrets.DIGITALOCEAN_FIREWALL_ID }} --droplet-ids $(doctl compute droplet get momomo-server --format ID --no-header)
        - if:  ${{ inputs.server_scaling_action == 'Down' }} 
          name: Scale Down
          run: doctl compute droplet delete momomo-server -f -v
