# This workflow will deploy a Java project to the remote server

name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build executable jar
        run: ./gradlew bootJar
      - name: Deploy the package to the remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build/libs
          remote: jarvis
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Run a script on remote server (start the application)
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd jarvis/
            mv jarvis-*.jar jarvis.jar
            kill $(ps aux | grep 'jarvis.jar' | grep -v grep | awk '{print $2}')
            java -jar jarvis.jar &
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"
