name: Delete infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Delete infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/JarvisGithubRole
        aws-region: eu-central-1

    - name: Start delete of CloudFormation stack
      run: |
        aws cloudformation delete-stack --stack-name jarvis-stack --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/JarvisCloudFormationLightsailRole
